/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computer.gltf -t
Author: Tuuttipingu (https://sketchfab.com/Tuuttipingu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-computer-71daf747a9b54b9299cc495533141eb5
Title: Sci-fi Computer
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    scifi_computer_screen_0: THREE.Mesh;
    scifi_computer_computer_0: THREE.Mesh;
    scifi_computer_keyboard_0: THREE.Mesh;
    scifi_computer_keys_0: THREE.Mesh;
  };
  materials: {
    screen: THREE.MeshStandardMaterial;
    computer: THREE.MeshStandardMaterial;
    keyboard: THREE.MeshStandardMaterial;
    keys: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/computer.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2.7, 0, -0.25]}>
        <group scale={0.9}>
          <mesh
            geometry={nodes.scifi_computer_screen_0.geometry}
            material={materials.screen}
          />
          <mesh
            geometry={nodes.scifi_computer_computer_0.geometry}
            material={materials.computer}
          />
          <mesh
            geometry={nodes.scifi_computer_keyboard_0.geometry}
            material={materials.keyboard}
          />
          <mesh
            geometry={nodes.scifi_computer_keys_0.geometry}
            material={materials.keys}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/computer.gltf");
